name: ${project.name}
main: studio.magemonkey.enigma.Enigma
authors: [ Travja, GoFlish ]
version: ${project.version}
depend: [ Codex ]
softdepend: [ WorldEdit, WorldGuard ]
api-version: 1.13
#commands:
#  chests: {}
