name: ${project.name}
main: com.promcteam.enigma.Enigma
authors: [ Travja, GoFlish ]
version: ${project.version}
depend: [ RiseCore ]
softdepend: [ WorldEdit, WorldGuard ]
api-version: 1.13
#commands:
#  chests: {}
